//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRP.Arbis.DataAccessLayer.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schools()
        {
            this.SchoolPosts = new HashSet<SchoolPosts>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string E_Mail { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
        public string SchoolType { get; set; }
    
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolPosts> SchoolPosts { get; set; }
    }
}
